version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: awesomeProject/web/Dockerfile
    # ports from container exposed to the docker machine and the guest machine
    ports:
      # 80 on the host, 8080 on the guest. Websever listens on 8080
      - "80:9000" # http
      - "443:443" # https
    # file with environment declarations for the container
    env_file:
      - web/.env
    # Link to containers in another service
    links:
      - db
    # sync workspace folder with /go
    volumes:
      - ../../../../.:/go
  db:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=citizix_user
      - MYSQL_DATABASE=citizix_db